---
title: "Behind the Numbers: How Racial Disparities Define Police-Related Fatalities"
toc: true
draft: FALSE
editor: 
  markdown: 
    wrap: sentence
---

## Introduction:

On a windy fall evening in Minneapolis, Minnesota in 2021, a community gathered, candles in hand, and their faces revealed their pain.
They were not just mourning for a loss, but also protesting for a pattern.
Among them was one old lady, who held a placard in hand that read, 'Justice for Daunte.' Daunte Wright, a 20-year-old young Black man, had been stopped and shot by the police during a traffic violation earlier this month.
The officer involved resigned and was charged with second-degree manslaughter pending investigation, but to those gathered, this was a familiar end to a grievously familiar story.

Daunte's story is not isolated.
Across the United States, the tapestry of names, faces, and faded candles tells a similar tale.
Data collected nationally reveals a stark reality: racial disparities pervade police-related fatalities, with Black individuals disproportionately represented.
These are not just statistics; they are sons and daughters, friends and neighbors, whose stories demand a closer look.

This analysis aims to peel back the layers of data surrounding police-related fatalities to uncover how deeply race is intertwined with these fatal encounters.
By examining the numbers, we seek to understand not only the scope of the disparities but also the human stories behind the statistics.

------------------------------------------------------------------------

## Racial Breakdown in Police Fatalities:

```{r}
police_race_counts <- table(police_f$Race)
police_race_prop <- prop.table(police_race_counts)

total_pop <- sum(us_dem$population)
us_race_prop <- tapply(us_dem$Total.Population, us_dem$race, sum) / total_pop
```

On a windy fall evening in Minneapolis, Minnesota in 2021, a community gathered, candles in hand, and their faces revealed their pain.
They were not just mourning for a loss, but also protesting for a pattern.
Among them was one old lady, who held a placard in hand that read, 'Justice for Daunte.' Daunte Wright, a 20-year-old young Black man, had been stopped and shot by the police during a traffic violation earlier this month.
The officer involved resigned and was charged with second-degree manslaughter pending investigation, but to those gathered, this was a familiar end to a grievously familiar story.

------------------------------------------------------------------------

## Rubric: On this page

You will

-   Title
    -   Your big picture page should have a creative/click-bait-y title/headline that provides a hint about your thesis.
-   Clarity of Explanation
    -   You should have a clear thesis/goal for this page. What are you trying to show? Make sure that you explain your analysis in detail but don't go into top much mathematics or statistics. The audience for this page is the general public (to the extent possible). Your thesis should be a statement, not a question.
    -   Each figure should be very polished and also not too complicated. There should be a clear interpretation of the figure so the figure has a clear purpose. Even something like a histogram can be difficult to interpret for non-experts.
-   Creativity
    -   Do your best to make things interesting. Think of a story. Think of how each part of your analysis supports the previous part or provides a different perspective.
-   This page should be self-contained.

**Note**: This page should have no code visible, i.e. use `#| echo: FALSE`.

------------------------------------------------------------------------

## Rubric: Other components

### Interactive

You will also be required to make an interactive dashboard like [this one](/flex/flex.html).

Your Big Data page should include a link to an interactive dashboard.
The dashboard should be created either using Shiny or FlexDashboard (or another tool with professor's approval).
This interactive component should in some way support your thesis from your big picture page.
Good interactives often provide both high-level understanding of the data while allowing a user to investigate specific scenarios, observations, subgroups, etc.

-   Quality and ease of use of the interactive components. Is it clear what can be explored using your interactive components? Does it enhance and reinforce your conclusions from the Big Picture? Plotly with default hover text will get no credit. Be creative!

### Video Recording

Make a video recording (probably using Zoom) demonstrating your interactive components.
You should provide a quick explanation of your data and demonstrate some of the conclusions from your EDA.
This video should be no longer than 4 minutes.
Include a link to your video (and password if needed) in your README.md file on your Github repository.
You are not required to provide a link on the website.
This can be presented by any subset of the team members.

### Rest of the Site

Finally, here are important things to keep in mind for the rest of the site.

The main title of your page is informative.
Each post has an author/description/informative title.
All lab required posts are present.
Each page (including the home page) has a nice featured image associated with it.
Your about page is up to date and clean.
You have removed the generic posts from the initial site template.
